gateways:
  postgres:
    connection:
      type: postgres
      host: host.docker.internal
      user: postgres
      password: admin123
      port: 5432
      database: retail_pricing

default_gateway: postgres

model_defaults:
  dialect: postgres
  start: 2026-03-16